* Table of content
1. [[Getting started with the project]]
   - [[Installing client side]]
   - [[Installing server side]]
2. [[Folder structure]]
   - [[Images]]
   - [[public]]
   - [[server]]
   - [[src]]
3. [[Example]]


* Getting started with the project

** Installing client side
root directory is the client side.
+ run npm install
  This will install all the required dependency for the project.
+ run npm start
  This will start the test server on the default browser.

** Installing server side
root/server is the server side directory
+ run npm install
  This will install all the required dependency for the project.
+ run nodemon index
  This will run the server side for the client.

* Folder structure
** Images
This contains test images for the project

** public
This folder is auto generated by the react library
+ [[file:public/index.html][index.html]] this is the main html in which react append
  AJX code from the src folder.
+ [[file:public/manifest.json][mainfest.json]] this file contains all the meta data for
  the website including icons and sort name and other things.

** server
+ [[file:server/db.js][db.js]] this file creates the return the connection object for
  the database.
+ [[file:server/index.js][index.js]] this file contains the all the route required by the
  client to function properly.

** src
This folder has the all the components required for the front end.

+ [[file:src/Assets][Assets]]
  This folder contains assest required by react
+ [[file:src/Components][Components]]
  This is the place where all the components lives.
  - [[file:src/Components/Med/][Med]]
    This directory contains all the things related to medicine and home page.
  - [[file:src/Components/Profile/][Profile]]
    This directory contains all the components related to profile page like.
    a. Changing user roles
    b. Updating medicine contains
    c. Adding Medicine
    d. Changing password
    e. Changing passphrase
  - [[file:src/Components/Static/][Static]]
    This folder contains all the static things like
    a. Loading page
    b. Login page
    c. Navbar
    d. Sign up page

* Example
** A example database is included in the root folder of the project. [[file:/rollingMeds.db][exampleDatabase]]

*** For Installation follow the below steps:
+ In MariaDB shell
  #+begin_src sql
    CREATE DATABASE rollingMeds;
  #+end_src
+ In shell
  #+begin_src shell
    mysql -u root -p rollingMeds < ./rollingMeds.db
  #+end_src
